/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.HomeAdminController;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author faizaaulia
 */
public class UpdateStatusTransaksiView extends javax.swing.JFrame {

    /**
     * Creates new form UpdateStatusTransaksiView
     */
    public UpdateStatusTransaksiView() {
        initComponents();
        btnUpdate.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        labelAlamat = new javax.swing.JLabel();
        labeTelp = new javax.swing.JLabel();
        labelStatus = new javax.swing.JLabel();
        labelLayanan = new javax.swing.JLabel();
        labelKelamin = new javax.swing.JLabel();
        labelTgl = new javax.swing.JLabel();
        labelBerat = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        labelNamanya = new javax.swing.JTextField();
        labelTelpnya = new javax.swing.JTextField();
        labelAlamatnya = new javax.swing.JTextField();
        labelKelaminnya = new javax.swing.JTextField();
        labelLayanannya = new javax.swing.JTextField();
        labelStatusnya = new javax.swing.JTextField();
        labelTanggalnya = new javax.swing.JTextField();
        labelBeratnya = new javax.swing.JTextField();
        labelTotalnya = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnUpdate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Data Transaksi");

        labelNama.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelNama.setText("Nama");

        labelAlamat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelAlamat.setText("Alamat");

        labeTelp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labeTelp.setText("No. Telp");

        labelStatus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelStatus.setText("Status");

        labelLayanan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelLayanan.setText("Layanan");

        labelKelamin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelKelamin.setText("Jenis Kelamin");

        labelTgl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelTgl.setText("Tgl Transaksi");

        labelBerat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelBerat.setText("Berat");

        labelTotal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelTotal.setText("Total");

        labelNamanya.setEditable(false);

        labelTelpnya.setEditable(false);

        labelAlamatnya.setEditable(false);

        labelKelaminnya.setEditable(false);

        labelLayanannya.setEditable(false);

        labelStatusnya.setEditable(false);

        labelTanggalnya.setEditable(false);

        labelBeratnya.setEditable(false);

        labelTotalnya.setEditable(false);

        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnBack.setText("BACK");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(labelNama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelAlamat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                            .addComponent(labelKelamin)
                            .addComponent(labeTelp))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelKelaminnya, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelNamanya, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelAlamatnya, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelLayanan, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelBerat)
                                            .addComponent(labelTotal)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                        .addComponent(labelTgl))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelTelpnya, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(labelStatus)))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelStatusnya, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelLayanannya, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(labelBeratnya, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelTotalnya, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTanggalnya, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNama)
                    .addComponent(labelLayanan)
                    .addComponent(labelNamanya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelLayanannya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labeTelp)
                    .addComponent(labelStatus)
                    .addComponent(labelTelpnya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelStatusnya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAlamat)
                    .addComponent(labelTgl)
                    .addComponent(labelAlamatnya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTanggalnya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKelamin)
                    .addComponent(labelBerat)
                    .addComponent(labelKelaminnya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelBeratnya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTotal)
                    .addComponent(labelTotalnya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnBack))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    public JButton getBtnUpdate() {
        return btnUpdate;
    }
    
    public JButton getBtnBack() {
        return btnBack;
    }

    public void setButtonUpdate(JButton buttonUpdate) {
        this.btnUpdate = buttonUpdate;
    }

    public void setLabelAlamatnya(String labelAlamatnya) {
        this.labelAlamatnya.setText(labelAlamatnya); 
    }

    public void setLabelBeratnya(String labelBeratnya) {
        this.labelBeratnya.setText(labelBeratnya + " Kg");
    }

    public void setLabelKelaminnya(String labelKelaminnya) {
        this.labelKelaminnya.setText(labelKelaminnya);
    }

    public void setLabelLayanannya(String labelLayanannya) {
        this.labelLayanannya.setText(labelLayanannya);
    }

    public void setLabelNamanya(String labelNamanya) {
        this.labelNamanya.setText(labelNamanya);
    }

    public void setLabelStatusnya(String labelStatusnya) {
        this.labelStatusnya.setText(labelStatusnya);
    }
    
    public void setLabelTanggalnya(String labelTanggalnya) {
        this.labelTanggalnya.setText(labelTanggalnya);
    }

    public void setLabelTelpnya(String labelTelpnya) {
        this.labelTelpnya.setText(labelTelpnya);
    }

    public void setLabelTotalnya(String labelTotalnya) {
        this.labelTotalnya.setText("Rp" + labelTotalnya);
    }

    public void addActionListener(HomeAdminController aThis) {
        btnUpdate.addActionListener(aThis);
        btnBack.addActionListener(aThis);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labeTelp;
    private javax.swing.JLabel labelAlamat;
    private javax.swing.JTextField labelAlamatnya;
    private javax.swing.JLabel labelBerat;
    private javax.swing.JTextField labelBeratnya;
    private javax.swing.JLabel labelKelamin;
    private javax.swing.JTextField labelKelaminnya;
    private javax.swing.JLabel labelLayanan;
    private javax.swing.JTextField labelLayanannya;
    private javax.swing.JLabel labelNama;
    private javax.swing.JTextField labelNamanya;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JTextField labelStatusnya;
    private javax.swing.JTextField labelTanggalnya;
    private javax.swing.JTextField labelTelpnya;
    private javax.swing.JLabel labelTgl;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JTextField labelTotalnya;
    // End of variables declaration//GEN-END:variables
}
