/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.HomeAdminController;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author faizaaulia
 */
public class UpdateStatusTransaksiView extends javax.swing.JFrame {

    /**
     * Creates new form UpdateStatusTransaksiView
     */
    public UpdateStatusTransaksiView() {
        initComponents();
        buttonUpdate.setVisible(false);
        tfUpdate.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        labelNamanya = new javax.swing.JLabel();
        labelAlamat = new javax.swing.JLabel();
        labelAlamatnya = new javax.swing.JLabel();
        labeTelp = new javax.swing.JLabel();
        labelTelpnya = new javax.swing.JLabel();
        labelStatus = new javax.swing.JLabel();
        labelLayanannya = new javax.swing.JLabel();
        labelLayanan = new javax.swing.JLabel();
        labelKelaminnya = new javax.swing.JLabel();
        labelKelamin = new javax.swing.JLabel();
        labelStatusnya = new javax.swing.JLabel();
        labelTgl = new javax.swing.JLabel();
        labelBerat = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        labelTanggalnya = new javax.swing.JLabel();
        labelBeratnya = new javax.swing.JLabel();
        labelTotalnya = new javax.swing.JLabel();
        buttonUpdate = new javax.swing.JButton();
        tfUpdate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Data Transaksi");

        labelNama.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelNama.setText("Nama");

        labelNamanya.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelNamanya.setText("namanya");

        labelAlamat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelAlamat.setText("Alamat");

        labelAlamatnya.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelAlamatnya.setText("alamatnya");

        labeTelp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labeTelp.setText("No. Telp");

        labelTelpnya.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelTelpnya.setText("telpnya");

        labelStatus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelStatus.setText("Status");

        labelLayanannya.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelLayanannya.setText("layanannya");

        labelLayanan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelLayanan.setText("Layanan");

        labelKelaminnya.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelKelaminnya.setText("Kelaminnya");

        labelKelamin.setText("Jenis Kelamin");

        labelStatusnya.setText("Statusnya");

        labelTgl.setText("Tgl Transaksi");

        labelBerat.setText("Berat");

        labelTotal.setText("Total");

        labelTanggalnya.setText("Tanggalnya");

        labelBeratnya.setText("Beratnya");

        labelTotalnya.setText("Totalnya");

        buttonUpdate.setText("Update");
        buttonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateActionPerformed(evt);
            }
        });

        tfUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(labelLayanan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                                .addComponent(labelNama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelAlamat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(labeTelp)
                            .addComponent(labelKelamin))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(labelLayanannya))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelAlamatnya)
                                    .addComponent(labelKelaminnya)
                                    .addComponent(labelTelpnya)
                                    .addComponent(labelNamanya, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTgl)
                            .addComponent(labelStatus)
                            .addComponent(labelBerat)
                            .addComponent(labelTotal))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelTotalnya)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonUpdate))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelTanggalnya)
                                    .addComponent(labelStatusnya))
                                .addGap(0, 203, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelBeratnya)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNama)
                    .addComponent(labelNamanya))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labeTelp)
                    .addComponent(labelTelpnya))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAlamat)
                    .addComponent(labelAlamatnya))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKelaminnya)
                    .addComponent(labelKelamin))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLayanan)
                    .addComponent(labelLayanannya))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelStatus)
                    .addComponent(labelStatusnya))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTgl)
                    .addComponent(labelTanggalnya))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBerat)
                    .addComponent(labelBeratnya)
                    .addComponent(tfUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTotal)
                    .addComponent(labelTotalnya)
                    .addComponent(buttonUpdate))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonUpdateActionPerformed

    private void tfUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUpdateActionPerformed

    public JButton getButtonUpdate() {
        return buttonUpdate;
    }

    public void setButtonUpdate(JButton buttonUpdate) {
        this.buttonUpdate = buttonUpdate;
    }

    public JLabel getLabelAlamatnya() {
        return labelAlamatnya;
    }

    public void setLabelAlamatnya(String labelAlamatnya) {
        this.labelAlamatnya.setText(labelAlamatnya); 
    }

    public JLabel getLabelBeratnya() {
        return labelBeratnya;
    }

    public void setLabelBeratnya(String labelBeratnya) {
        this.labelBeratnya.setText(labelBeratnya);
    }

    public JLabel getLabelKelaminnya() {
        return labelKelaminnya;
    }

    public void setLabelKelaminnya(String labelKelaminnya) {
        this.labelKelaminnya.setText(labelKelaminnya);
    }

    public JLabel getLabelLayanannya() {
        return labelLayanannya;
    }

    public void setLabelLayanannya(String labelLayanannya) {
        this.labelLayanannya.setText(labelLayanannya);
    }

    public JLabel getLabelNamanya() {
        return labelNamanya;
    }

    public void setLabelNamanya(String labelNamanya) {
        this.labelNamanya.setText(labelNamanya);
    }

    public JLabel getLabelStatusnya() {
        return labelStatusnya;
    }

    public void setLabelStatusnya(String labelStatusnya) {
        this.labelStatusnya.setText(labelStatusnya);
    }

    public JLabel getLabelTanggalnya() {
        return labelTanggalnya;
    }

    public void setLabelTanggalnya(String labelTanggalnya) {
        this.labelTanggalnya.setText(labelTanggalnya);
    }

    public JLabel getLabelTelpnya() {
        return labelTelpnya;
    }

    public void setLabelTelpnya(String labelTelpnya) {
        this.labelTelpnya.setText(labelTelpnya);
    }

    public JLabel getLabelTotalnya() {
        return labelTotalnya;
    }

    public void setLabelTotalnya(String labelTotalnya) {
        this.labelTotalnya.setText(labelTotalnya);
    }

    public JTextField getTfUpdate() {
        return tfUpdate;
    }

    public void setTfUpdate(JTextField tfUpdate) {
        this.tfUpdate = tfUpdate;
    }

    public void addActionListener(HomeAdminController aThis) {
        buttonUpdate.addActionListener(aThis);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateStatusTransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateStatusTransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateStatusTransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateStatusTransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateStatusTransaksiView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labeTelp;
    private javax.swing.JLabel labelAlamat;
    private javax.swing.JLabel labelAlamatnya;
    private javax.swing.JLabel labelBerat;
    private javax.swing.JLabel labelBeratnya;
    private javax.swing.JLabel labelKelamin;
    private javax.swing.JLabel labelKelaminnya;
    private javax.swing.JLabel labelLayanan;
    private javax.swing.JLabel labelLayanannya;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelNamanya;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JLabel labelStatusnya;
    private javax.swing.JLabel labelTanggalnya;
    private javax.swing.JLabel labelTelpnya;
    private javax.swing.JLabel labelTgl;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JLabel labelTotalnya;
    private javax.swing.JTextField tfUpdate;
    // End of variables declaration//GEN-END:variables
}
