/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.HomeAdminController;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author faizaaulia
 */
public class UpdateStatusTransaksiView extends javax.swing.JFrame {

    /**
     * Creates new form UpdateStatusTransaksiView
     */
    public UpdateStatusTransaksiView() {
        initComponents();
        btnUpdate.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        labelAlamat = new javax.swing.JLabel();
        labeTelp = new javax.swing.JLabel();
        labelStatus = new javax.swing.JLabel();
        labelLayanan = new javax.swing.JLabel();
        labelKelamin = new javax.swing.JLabel();
        labelTgl = new javax.swing.JLabel();
        labelBerat = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        tfNamanya = new javax.swing.JTextField();
        tfNoTelpnya = new javax.swing.JTextField();
        tfAlamatnya = new javax.swing.JTextField();
        tfJKnya = new javax.swing.JTextField();
        tfLayanannya = new javax.swing.JTextField();
        tfStatusnya = new javax.swing.JTextField();
        tfTanggalnya = new javax.swing.JTextField();
        tfBeratnya = new javax.swing.JTextField();
        tfTotalnya = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnUpdate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        labelNama1 = new javax.swing.JLabel();
        tfNoTransaksi = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Data Transaksi");

        labelNama.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelNama.setText("Nama");

        labelAlamat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelAlamat.setText("Alamat");

        labeTelp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labeTelp.setText("No. Telp");

        labelStatus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelStatus.setText("Status");

        labelLayanan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelLayanan.setText("Layanan");

        labelKelamin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelKelamin.setText("Jenis Kelamin");

        labelTgl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelTgl.setText("Tgl Transaksi");

        labelBerat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelBerat.setText("Berat");

        labelTotal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelTotal.setText("Total");

        tfNamanya.setEditable(false);

        tfNoTelpnya.setEditable(false);

        tfAlamatnya.setEditable(false);

        tfJKnya.setEditable(false);

        tfLayanannya.setEditable(false);

        tfStatusnya.setEditable(false);

        tfTanggalnya.setEditable(false);

        tfBeratnya.setEditable(false);

        tfTotalnya.setEditable(false);

        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnBack.setText("BACK");

        labelNama1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelNama1.setText("No. Transaksi");

        tfNoTransaksi.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(labelNama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(labelAlamat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(labelKelamin)
                                    .addComponent(labeTelp))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfJKnya, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfNamanya, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfAlamatnya, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfNoTelpnya, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNama1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNoTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelLayanan, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelBerat)
                                    .addComponent(labelTotal)
                                    .addComponent(labelStatus))
                                .addGap(18, 40, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelTgl)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfStatusnya, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfLayanannya, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(tfBeratnya, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfTotalnya, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfTanggalnya, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLayanan)
                    .addComponent(tfLayanannya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNama1)
                    .addComponent(tfNoTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelStatus)
                            .addComponent(tfStatusnya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTgl)
                            .addComponent(tfTanggalnya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelBerat)
                            .addComponent(tfBeratnya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTotal)
                            .addComponent(tfTotalnya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUpdate)
                            .addComponent(btnBack))
                        .addContainerGap(14, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNama)
                            .addComponent(tfNamanya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labeTelp)
                            .addComponent(tfNoTelpnya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelAlamat)
                            .addComponent(tfAlamatnya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelKelamin)
                            .addComponent(tfJKnya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    public JButton getBtnUpdate() {
        return btnUpdate;
    }
    
    public JButton getBtnBack() {
        return btnBack;
    }

    public void setButtonUpdate(JButton buttonUpdate) {
        this.btnUpdate = buttonUpdate;
    }
    
    public void setTfNoTransaksi(String tfTransaksi) {
        this.tfNoTransaksi.setText(tfTransaksi);
    }

    public void setTfAlamatnya(String tfAlamatnya) {
        this.tfAlamatnya.setText(tfAlamatnya); 
    }

    public void setTfBeratnya(String tfBeratnya) {
        this.tfBeratnya.setText(tfBeratnya + " Kg");
    }

    public void setTfJK(String tfJK) {
        this.tfJKnya.setText(tfJK);
    }

    public void setTfLayanannya(String tfLayanannya) {
        this.tfLayanannya.setText(tfLayanannya);
    }

    public void setTfNamanya(String tfNamanya) {
        this.tfNamanya.setText(tfNamanya);
    }

    public void setTfStatusnya(String tfStatusnya) {
        this.tfStatusnya.setText(tfStatusnya);
    }
    
    public void setTfTanggalnya(String tfTanggalnya) {
        this.tfTanggalnya.setText(tfTanggalnya);
    }

    public void setTfNoTelpnya(String tfTelpnya) {
        this.tfNoTelpnya.setText(tfTelpnya);
    }

    public void setTfTotalnya(String tfTotalnya) {
        this.tfTotalnya.setText("Rp" + tfTotalnya);
    }

    public void addActionListener(HomeAdminController aThis) {
        btnUpdate.addActionListener(aThis);
        btnBack.addActionListener(aThis);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labeTelp;
    private javax.swing.JLabel labelAlamat;
    private javax.swing.JLabel labelBerat;
    private javax.swing.JLabel labelKelamin;
    private javax.swing.JLabel labelLayanan;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelNama1;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JLabel labelTgl;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JTextField tfAlamatnya;
    private javax.swing.JTextField tfBeratnya;
    private javax.swing.JTextField tfJKnya;
    private javax.swing.JTextField tfLayanannya;
    private javax.swing.JTextField tfNamanya;
    private javax.swing.JTextField tfNoTelpnya;
    private javax.swing.JTextField tfNoTransaksi;
    private javax.swing.JTextField tfStatusnya;
    private javax.swing.JTextField tfTanggalnya;
    private javax.swing.JTextField tfTotalnya;
    // End of variables declaration//GEN-END:variables
}
